/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procedimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sarmientos
 */
public class PagoTotal extends javax.swing.JFrame {

    /**
     * Creates new form PagoTotal
     */
    public PagoTotal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtSueldoBase = new javax.swing.JTextField();
        txthijos = new javax.swing.JTextField();
        txtBono = new javax.swing.JTextField();
        txtSueldoTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("        PAGO TOTAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 30));

        jLabel2.setText("Sueldo Base");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Numero De Hijos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel4.setText("Total Bonificacion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel5.setText("Sueldo Final");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        txtSueldoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoBaseActionPerformed(evt);
            }
        });
        txtSueldoBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoBaseKeyTyped(evt);
            }
        });
        getContentPane().add(txtSueldoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, -1));

        txthijos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthijosKeyTyped(evt);
            }
        });
        getContentPane().add(txthijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 70, -1));
        getContentPane().add(txtBono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, -1));

        txtSueldoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtSueldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSueldoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoBaseActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
     txtSueldoBase.setText("");
     txthijos.setText("");
     txtBono.setText("");
     txtSueldoTotal.setText("");
     txtSueldoBase.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtSueldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoTotalActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int nhijos;
        double sbase, bono, total;
        String btotal, sfinal;

     if(txtSueldoBase.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite el sueldo base","error", JOptionPane.ERROR_MESSAGE);  
        txtSueldoBase.requestFocusInWindow();
        txtSueldoBase.selectAll();
     }  
     else if(txthijos.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite número de hijos","error", JOptionPane.ERROR_MESSAGE);  
        txthijos.requestFocusInWindow(); 
         txthijos.selectAll();    
     }
     else{
     sbase=Double.parseDouble(txtSueldoBase.getText());
     nhijos=Integer.parseInt(txthijos.getText());
     
     if(nhijos==0){  
     }
    bono = nhijos*80000;
    total = bono+sbase;
    
    btotal=String.valueOf(bono);
    txtBono.setText (btotal);    
    
    sfinal=String.valueOf(total);
    txtSueldoTotal.setText (sfinal);      
         
     }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void txtSueldoBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoBaseKeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume();
    }//GEN-LAST:event_txtSueldoBaseKeyTyped

    private void txthijosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthijosKeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume();
              
          }
    }//GEN-LAST:event_txthijosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoTotal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBono;
    private javax.swing.JTextField txtSueldoBase;
    private javax.swing.JTextField txtSueldoTotal;
    private javax.swing.JTextField txthijos;
    // End of variables declaration//GEN-END:variables
}
